import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding progression system...\n");

  // ============================================================================
  // BADGES
  // ============================================================================
  console.log("📛 Seeding badges...");

  const badges = [
    // ==================== PROGRESS BADGES ====================
    {
      code: "first_steps",
      name: "First Steps",
      description: "Complete your first topic",
      category: "PROGRESS" as const,
      tier: "BRONZE" as const,
      rarity: "COMMON" as const,
      criteria: { type: "topic_completion", count: 1 },
      xpReward: 50,
      sortOrder: 1,
    },
    {
      code: "rising_star",
      name: "Rising Star",
      description: "Improve your accuracy by 10% or more in any topic",
      category: "PROGRESS" as const,
      tier: "BRONZE" as const,
      rarity: "COMMON" as const,
      criteria: { type: "accuracy_improvement", minImprovement: 0.1 },
      xpReward: 75,
      sortOrder: 2,
    },
    {
      code: "comeback_kid",
      name: "Comeback Kid",
      description: "Return after 7+ days away and improve your performance",
      category: "PROGRESS" as const,
      tier: "SILVER" as const,
      rarity: "UNCOMMON" as const,
      criteria: { type: "comeback", minDaysAway: 7, mustImprove: true },
      xpReward: 100,
      sortOrder: 3,
    },
    {
      code: "steady_climber",
      name: "Steady Climber",
      description: "Improve your rating for 3 weeks in a row",
      category: "PROGRESS" as const,
      tier: "SILVER" as const,
      rarity: "UNCOMMON" as const,
      criteria: { type: "consecutive_improvement", weeks: 3 },
      xpReward: 150,
      sortOrder: 4,
    },
    {
      code: "breakthrough",
      name: "Breakthrough",
      description: "Jump from Bronze to Silver or higher mastery in a single session",
      category: "PROGRESS" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "tier_jump", fromTier: "BRONZE", minJump: 1 },
      xpReward: 200,
      sortOrder: 5,
    },
    {
      code: "marathon_runner",
      name: "Marathon Runner",
      description: "Answer 100 questions",
      category: "PROGRESS" as const,
      tier: "BRONZE" as const,
      rarity: "COMMON" as const,
      criteria: { type: "questions_answered", count: 100 },
      xpReward: 100,
      sortOrder: 6,
    },
    {
      code: "scholars_journey",
      name: "Scholar's Journey",
      description: "Complete 50% of your curriculum",
      category: "PROGRESS" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "curriculum_completion", percentage: 0.5 },
      xpReward: 300,
      sortOrder: 7,
    },
    {
      code: "question_century",
      name: "Question Century",
      description: "Answer 100 questions in a single day",
      category: "PROGRESS" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "daily_questions", count: 100 },
      xpReward: 250,
      sortOrder: 8,
    },

    // ==================== STREAK BADGES ====================
    {
      code: "streak_week_warrior",
      name: "Week Warrior",
      description: "Maintain a 7-day learning streak",
      category: "STREAK" as const,
      tier: "BRONZE" as const,
      rarity: "COMMON" as const,
      criteria: { type: "streak", days: 7 },
      xpReward: 100,
      sortOrder: 10,
    },
    {
      code: "streak_fortnight_force",
      name: "Fortnight Force",
      description: "Maintain a 14-day learning streak",
      category: "STREAK" as const,
      tier: "SILVER" as const,
      rarity: "UNCOMMON" as const,
      criteria: { type: "streak", days: 14 },
      xpReward: 150,
      sortOrder: 11,
    },
    {
      code: "streak_month_master",
      name: "Month Master",
      description: "Maintain a 30-day learning streak",
      category: "STREAK" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "streak", days: 30 },
      xpReward: 300,
      unlocksBanner: "banner_phoenix_rising",
      sortOrder: 12,
    },
    {
      code: "streak_quarter_quest",
      name: "Quarter Quest",
      description: "Maintain a 90-day learning streak",
      category: "STREAK" as const,
      tier: "PLATINUM" as const,
      rarity: "EPIC" as const,
      criteria: { type: "streak", days: 90 },
      xpReward: 500,
      unlocksTitle: "title_dedicated_scholar",
      sortOrder: 13,
    },
    {
      code: "streak_century_scholar",
      name: "Century Scholar",
      description: "Maintain a 100-day learning streak",
      category: "STREAK" as const,
      tier: "PLATINUM" as const,
      rarity: "EPIC" as const,
      criteria: { type: "streak", days: 100 },
      xpReward: 750,
      sortOrder: 14,
    },
    {
      code: "streak_year_round",
      name: "Year-Round Learner",
      description: "Maintain a 365-day learning streak",
      category: "STREAK" as const,
      tier: "DIAMOND" as const,
      rarity: "LEGENDARY" as const,
      criteria: { type: "streak", days: 365 },
      xpReward: 2000,
      unlocksBanner: "banner_eternal_flame",
      unlocksTitle: "title_legendary_scholar",
      sortOrder: 15,
    },
    {
      code: "streak_resilient",
      name: "Resilient",
      description: "Restore your streak using grace period 3 times",
      category: "STREAK" as const,
      tier: "SILVER" as const,
      rarity: "UNCOMMON" as const,
      criteria: { type: "grace_restores", count: 3 },
      xpReward: 100,
      sortOrder: 16,
    },
    {
      code: "streak_shield_bearer",
      name: "Shield Bearer",
      description: "Earn 5 streak shields",
      category: "STREAK" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "shields_earned", count: 5 },
      xpReward: 200,
      sortOrder: 17,
    },

    // ==================== MASTERY BADGES (Template - per topic) ====================
    // These would be generated dynamically per topic, but here are examples
    {
      code: "mastery_math_bronze",
      name: "Math Learner",
      description: "Achieve 60%+ accuracy on 10+ math questions",
      category: "MASTERY" as const,
      tier: "BRONZE" as const,
      rarity: "COMMON" as const,
      criteria: { type: "mastery", subject: "MATH", minAccuracy: 0.6, minQuestions: 10 },
      xpReward: 50,
      sortOrder: 20,
    },
    {
      code: "mastery_math_silver",
      name: "Math Scholar",
      description: "Achieve 70%+ accuracy on 20+ math questions",
      category: "MASTERY" as const,
      tier: "SILVER" as const,
      rarity: "UNCOMMON" as const,
      criteria: { type: "mastery", subject: "MATH", minAccuracy: 0.7, minQuestions: 20 },
      xpReward: 100,
      sortOrder: 21,
    },
    {
      code: "mastery_math_gold",
      name: "Math Expert",
      description: "Achieve 80%+ accuracy on 30+ math questions",
      category: "MASTERY" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "mastery", subject: "MATH", minAccuracy: 0.8, minQuestions: 30 },
      xpReward: 200,
      sortOrder: 22,
    },
    {
      code: "mastery_math_platinum",
      name: "Math Master",
      description: "Achieve 90%+ accuracy on 50+ math questions",
      category: "MASTERY" as const,
      tier: "PLATINUM" as const,
      rarity: "EPIC" as const,
      criteria: { type: "mastery", subject: "MATH", minAccuracy: 0.9, minQuestions: 50 },
      xpReward: 400,
      sortOrder: 23,
    },
    {
      code: "mastery_math_diamond",
      name: "Math Sage",
      description: "Achieve 95%+ accuracy on 75+ math questions",
      category: "MASTERY" as const,
      tier: "DIAMOND" as const,
      rarity: "LEGENDARY" as const,
      criteria: { type: "mastery", subject: "MATH", minAccuracy: 0.95, minQuestions: 75 },
      xpReward: 750,
      unlocksTitle: "title_math_wizard",
      sortOrder: 24,
    },

    // ==================== CHALLENGE BADGES ====================
    {
      code: "challenge_storm_survivor",
      name: "Storm Survivor",
      description: "Complete a Puzzle Storm session",
      category: "CHALLENGE" as const,
      tier: "BRONZE" as const,
      rarity: "COMMON" as const,
      criteria: { type: "puzzle_storm_complete", minScore: 1 },
      xpReward: 50,
      sortOrder: 30,
    },
    {
      code: "challenge_storm_master",
      name: "Storm Master",
      description: "Score 50+ in a Puzzle Storm",
      category: "CHALLENGE" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "puzzle_storm_complete", minScore: 50 },
      xpReward: 200,
      sortOrder: 31,
    },
    {
      code: "challenge_streak_legend",
      name: "Streak Legend",
      description: "Reach 25+ correct answers in Puzzle Streak mode",
      category: "CHALLENGE" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "puzzle_streak_score", minScore: 25 },
      xpReward: 250,
      sortOrder: 32,
    },
    {
      code: "challenge_daily_devotee",
      name: "Daily Devotee",
      description: "Complete 7 Daily Challenges",
      category: "CHALLENGE" as const,
      tier: "SILVER" as const,
      rarity: "UNCOMMON" as const,
      criteria: { type: "daily_challenges_completed", count: 7 },
      xpReward: 150,
      sortOrder: 33,
    },
    {
      code: "challenge_daily_champion",
      name: "Daily Champion",
      description: "Finish in the top 10% of a Daily Challenge",
      category: "CHALLENGE" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "daily_challenge_percentile", maxPercentile: 10 },
      xpReward: 300,
      sortOrder: 34,
    },
    {
      code: "challenge_speed_demon",
      name: "Speed Demon",
      description: "Complete a quiz in under 50% of the average time with 80%+ accuracy",
      category: "CHALLENGE" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "speed_completion", maxTimePercent: 0.5, minAccuracy: 0.8 },
      xpReward: 250,
      sortOrder: 35,
    },
    {
      code: "challenge_perfect_storm",
      name: "Perfect Storm",
      description: "Achieve 100% accuracy in a Puzzle Storm session",
      category: "CHALLENGE" as const,
      tier: "PLATINUM" as const,
      rarity: "EPIC" as const,
      criteria: { type: "puzzle_storm_perfect" },
      xpReward: 500,
      sortOrder: 36,
    },

    // ==================== EXPLORATION BADGES ====================
    {
      code: "explore_curious_mind",
      name: "Curious Mind",
      description: "Attempt questions from 5 different topics",
      category: "EXPLORATION" as const,
      tier: "BRONZE" as const,
      rarity: "COMMON" as const,
      criteria: { type: "topics_attempted", count: 5 },
      xpReward: 75,
      sortOrder: 40,
    },
    {
      code: "explore_subject_explorer",
      name: "Subject Explorer",
      description: "Complete at least 1 topic in each available subject",
      category: "EXPLORATION" as const,
      tier: "SILVER" as const,
      rarity: "UNCOMMON" as const,
      criteria: { type: "all_subjects_attempted" },
      xpReward: 200,
      sortOrder: 41,
    },
    {
      code: "explore_grade_adventurer",
      name: "Grade Adventurer",
      description: "Try questions from a grade level above your current one",
      category: "EXPLORATION" as const,
      tier: "SILVER" as const,
      rarity: "UNCOMMON" as const,
      criteria: { type: "above_grade_attempt" },
      xpReward: 150,
      sortOrder: 42,
    },
    {
      code: "explore_deep_diver",
      name: "Deep Diver",
      description: "Complete all subtopics within a single topic",
      category: "EXPLORATION" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "all_subtopics_complete" },
      xpReward: 250,
      sortOrder: 43,
    },
    {
      code: "explore_polymath",
      name: "Polymath",
      description: "Achieve Silver+ mastery in 3 different subjects",
      category: "EXPLORATION" as const,
      tier: "PLATINUM" as const,
      rarity: "EPIC" as const,
      criteria: { type: "multi_subject_mastery", subjects: 3, minTier: "SILVER" },
      xpReward: 500,
      unlocksTitle: "title_polymath",
      sortOrder: 44,
    },
    {
      code: "explore_well_rounded",
      name: "Well Rounded",
      description: "Attempt all available question types",
      category: "EXPLORATION" as const,
      tier: "SILVER" as const,
      rarity: "UNCOMMON" as const,
      criteria: { type: "all_question_types" },
      xpReward: 150,
      sortOrder: 45,
    },

    // ==================== SPECIAL BADGES ====================
    {
      code: "special_early_adopter",
      name: "Early Adopter",
      description: "Joined during the beta period",
      category: "SPECIAL" as const,
      tier: "GOLD" as const,
      rarity: "RARE" as const,
      criteria: { type: "special", event: "beta_signup" },
      xpReward: 500,
      unlocksBanner: "banner_pioneer",
      isHidden: true,
      sortOrder: 50,
    },
    {
      code: "special_founding_scholar",
      name: "Founding Scholar",
      description: "One of the first 1000 users",
      category: "SPECIAL" as const,
      tier: "PLATINUM" as const,
      rarity: "EPIC" as const,
      criteria: { type: "special", event: "first_1000" },
      xpReward: 1000,
      unlocksTitle: "title_founding_scholar",
      isHidden: true,
      sortOrder: 51,
    },
  ];

  for (const badge of badges) {
    await prisma.badgeDefinition.upsert({
      where: { code: badge.code },
      update: badge,
      create: badge,
    });
  }
  console.log(`   ✅ Created ${badges.length} badges\n`);

  // ============================================================================
  // ACHIEVEMENTS
  // ============================================================================
  console.log("🏆 Seeding achievements...");

  const achievements = [
    // Academic Achievements
    {
      code: "first_topic_master",
      name: "First Topic Master",
      description: "Achieve Gold mastery in any topic",
      category: "ACADEMIC" as const,
      difficulty: "MEDIUM" as const,
      criteria: { type: "topic_mastery", minTier: "GOLD", count: 1 },
      hasProgress: false,
      xpReward: 300,
      titleReward: "title_topic_master",
      sortOrder: 1,
    },
    {
      code: "subject_champion_math",
      name: "Subject Champion - Mathematics",
      description: "Achieve Gold+ mastery in 10+ math topics",
      category: "ACADEMIC" as const,
      difficulty: "HARD" as const,
      criteria: { type: "topic_mastery_count", subject: "MATH", minTier: "GOLD", minCount: 10 },
      hasProgress: true,
      progressMax: 10,
      xpReward: 1000,
      bannerReward: "banner_math_champion",
      titleReward: "title_mathematician",
      sortOrder: 2,
    },
    {
      code: "grade_complete",
      name: "Grade Complete",
      description: "Achieve 80%+ accuracy across all topics in your grade level",
      category: "ACADEMIC" as const,
      difficulty: "HARD" as const,
      criteria: { type: "grade_completion", minAccuracy: 0.8 },
      hasProgress: true,
      xpReward: 1500,
      iconReward: "icon_graduation_cap",
      sortOrder: 3,
    },
    {
      code: "curriculum_explorer",
      name: "Curriculum Explorer",
      description: "Complete content from 3+ grade levels",
      category: "ACADEMIC" as const,
      difficulty: "HARD" as const,
      criteria: { type: "multi_grade", minGrades: 3 },
      hasProgress: true,
      progressMax: 3,
      xpReward: 800,
      titleReward: "title_explorer",
      sortOrder: 4,
    },
    {
      code: "perfect_topic",
      name: "Perfect Topic",
      description: "Achieve 100% accuracy on a topic (minimum 20 questions)",
      category: "ACADEMIC" as const,
      difficulty: "LEGENDARY" as const,
      criteria: { type: "perfect_topic", minQuestions: 20 },
      hasProgress: false,
      xpReward: 1000,
      badgeReward: "mastery_perfectionist",
      sortOrder: 5,
    },

    // Challenge Achievements
    {
      code: "storm_chaser",
      name: "Storm Chaser",
      description: "Complete 10 Puzzle Storm sessions",
      category: "CHALLENGE" as const,
      difficulty: "MEDIUM" as const,
      criteria: { type: "puzzle_storm_count", count: 10 },
      hasProgress: true,
      progressMax: 10,
      xpReward: 500,
      titleReward: "title_storm_chaser",
      sortOrder: 10,
    },
    {
      code: "daily_devotee_30",
      name: "Daily Devotee",
      description: "Complete 30 Daily Challenges",
      category: "CHALLENGE" as const,
      difficulty: "MEDIUM" as const,
      criteria: { type: "daily_challenges", count: 30 },
      hasProgress: true,
      progressMax: 30,
      xpReward: 600,
      bannerReward: "banner_daily_champion",
      sortOrder: 11,
    },
    {
      code: "streak_champion",
      name: "Streak Champion",
      description: "Reach 50+ correct in Puzzle Streak mode",
      category: "CHALLENGE" as const,
      difficulty: "HARD" as const,
      criteria: { type: "puzzle_streak_high", minScore: 50 },
      hasProgress: false,
      xpReward: 750,
      iconReward: "icon_streak_flame",
      sortOrder: 12,
    },
    {
      code: "speed_scholar",
      name: "Speed Scholar",
      description: "Finish in top 10% time on 5 different quizzes",
      category: "CHALLENGE" as const,
      difficulty: "HARD" as const,
      criteria: { type: "speed_top_percentile", percentile: 10, count: 5 },
      hasProgress: true,
      progressMax: 5,
      xpReward: 600,
      titleReward: "title_speed_scholar",
      sortOrder: 13,
    },

    // Milestone Achievements
    {
      code: "century_club",
      name: "Century",
      description: "Answer 100 questions",
      category: "MILESTONE" as const,
      difficulty: "EASY" as const,
      criteria: { type: "questions_total", count: 100 },
      hasProgress: true,
      progressMax: 100,
      xpReward: 200,
      sortOrder: 20,
    },
    {
      code: "thousand_club",
      name: "Thousand Club",
      description: "Answer 1,000 questions",
      category: "MILESTONE" as const,
      difficulty: "MEDIUM" as const,
      criteria: { type: "questions_total", count: 1000 },
      hasProgress: true,
      progressMax: 1000,
      xpReward: 500,
      titleReward: "title_dedicated",
      sortOrder: 21,
    },
    {
      code: "ten_thousand_club",
      name: "Ten Thousand Club",
      description: "Answer 10,000 questions",
      category: "MILESTONE" as const,
      difficulty: "LEGENDARY" as const,
      criteria: { type: "questions_total", count: 10000 },
      hasProgress: true,
      progressMax: 10000,
      xpReward: 2000,
      titleReward: "title_legendary_scholar",
      bannerReward: "banner_legend",
      sortOrder: 22,
    },
    {
      code: "time_invested_10h",
      name: "Time Invested",
      description: "Spend 10 hours learning",
      category: "MILESTONE" as const,
      difficulty: "MEDIUM" as const,
      criteria: { type: "time_spent", hours: 10 },
      hasProgress: true,
      progressMax: 600, // minutes
      xpReward: 400,
      bannerReward: "banner_time_keeper",
      sortOrder: 23,
    },
    {
      code: "scholars_year",
      name: "Scholar's Year",
      description: "Maintain a 365-day streak",
      category: "MILESTONE" as const,
      difficulty: "LEGENDARY" as const,
      criteria: { type: "streak_milestone", days: 365 },
      hasProgress: true,
      progressMax: 365,
      xpReward: 5000,
      titleReward: "title_year_round_scholar",
      bannerReward: "banner_eternal_flame",
      iconReward: "icon_golden_crown",
      sortOrder: 24,
    },
  ];

  for (const achievement of achievements) {
    await prisma.achievementDefinition.upsert({
      where: { code: achievement.code },
      update: achievement,
      create: achievement,
    });
  }
  console.log(`   ✅ Created ${achievements.length} achievements\n`);

  // ============================================================================
  // COSMETIC ITEMS
  // ============================================================================
  console.log("🎨 Seeding cosmetic items...");

  const cosmetics = [
    // ==================== DEFAULT BANNERS ====================
    {
      code: "banner_default_blue",
      name: "Ocean Blue",
      description: "A calming blue gradient",
      type: "BANNER" as const,
      rarity: "COMMON" as const,
      unlockMethod: "DEFAULT" as const,
      unlockCriteria: Prisma.JsonNull,
      sortOrder: 1,
    },
    {
      code: "banner_default_green",
      name: "Forest Green",
      description: "A refreshing green gradient",
      type: "BANNER" as const,
      rarity: "COMMON" as const,
      unlockMethod: "DEFAULT" as const,
      unlockCriteria: Prisma.JsonNull,
      sortOrder: 2,
    },
    {
      code: "banner_default_purple",
      name: "Royal Purple",
      description: "A majestic purple gradient",
      type: "BANNER" as const,
      rarity: "COMMON" as const,
      unlockMethod: "DEFAULT" as const,
      unlockCriteria: Prisma.JsonNull,
      sortOrder: 3,
    },

    // ==================== TIER-UNLOCKED BANNERS ====================
    {
      code: "banner_sprout_meadow",
      name: "Spring Meadow",
      description: "Fresh greens of new growth",
      type: "BANNER" as const,
      rarity: "COMMON" as const,
      unlockMethod: "TIER" as const,
      unlockCriteria: { academicTier: "SPROUT" },
      sortOrder: 10,
    },
    {
      code: "banner_sapling_forest",
      name: "Deep Forest",
      description: "Rich woodland colors",
      type: "BANNER" as const,
      rarity: "UNCOMMON" as const,
      unlockMethod: "TIER" as const,
      unlockCriteria: { academicTier: "SAPLING" },
      sortOrder: 11,
    },
    {
      code: "banner_tree_mountain",
      name: "Mountain Vista",
      description: "Majestic peaks at sunrise",
      type: "BANNER" as const,
      rarity: "UNCOMMON" as const,
      unlockMethod: "TIER" as const,
      unlockCriteria: { academicTier: "TREE" },
      sortOrder: 12,
    },
    {
      code: "banner_grove_aurora",
      name: "Northern Lights",
      description: "Dancing aurora borealis",
      type: "BANNER" as const,
      rarity: "RARE" as const,
      unlockMethod: "TIER" as const,
      unlockCriteria: { academicTier: "GROVE" },
      sortOrder: 13,
    },
    {
      code: "banner_forest_cosmos",
      name: "Cosmic Dreams",
      description: "Swirling galaxies and nebulae",
      type: "BANNER" as const,
      rarity: "EPIC" as const,
      unlockMethod: "TIER" as const,
      unlockCriteria: { academicTier: "FOREST" },
      sortOrder: 14,
    },
    {
      code: "banner_ancient_celestial",
      name: "Celestial Guardian",
      description: "Ancient stars watching over all",
      type: "BANNER" as const,
      rarity: "LEGENDARY" as const,
      unlockMethod: "TIER" as const,
      unlockCriteria: { academicTier: "ANCIENT_FOREST" },
      sortOrder: 15,
    },

    // ==================== BADGE-UNLOCKED BANNERS ====================
    {
      code: "banner_phoenix_rising",
      name: "Phoenix Rising",
      description: "Rise from the ashes of yesterday",
      type: "BANNER" as const,
      rarity: "RARE" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "streak_month_master" },
      sortOrder: 20,
    },
    {
      code: "banner_eternal_flame",
      name: "Eternal Flame",
      description: "A fire that never dies",
      type: "BANNER" as const,
      rarity: "LEGENDARY" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "streak_year_round" },
      sortOrder: 21,
    },
    {
      code: "banner_pioneer",
      name: "Pioneer Spirit",
      description: "For those who dared to begin",
      type: "BANNER" as const,
      rarity: "RARE" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "special_early_adopter" },
      sortOrder: 22,
    },
    {
      code: "banner_math_champion",
      name: "Mathematical Mastery",
      description: "Numbers bow to your will",
      type: "BANNER" as const,
      rarity: "EPIC" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "subject_champion_math" },
      sortOrder: 23,
    },
    {
      code: "banner_daily_champion",
      name: "Champion's Glory",
      description: "Daily dedication rewarded",
      type: "BANNER" as const,
      rarity: "RARE" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "daily_devotee_30" },
      sortOrder: 24,
    },
    {
      code: "banner_time_keeper",
      name: "Time Keeper",
      description: "Master of moments",
      type: "BANNER" as const,
      rarity: "RARE" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "time_invested_10h" },
      sortOrder: 25,
    },
    {
      code: "banner_legend",
      name: "Living Legend",
      description: "Your dedication is legendary",
      type: "BANNER" as const,
      rarity: "LEGENDARY" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "ten_thousand_club" },
      sortOrder: 26,
    },

    // ==================== DEFAULT ICONS ====================
    {
      code: "icon_default_student",
      name: "Student",
      description: "A fresh-faced learner",
      type: "ICON" as const,
      rarity: "COMMON" as const,
      unlockMethod: "DEFAULT" as const,
      unlockCriteria: Prisma.JsonNull,
      sortOrder: 100,
    },
    {
      code: "icon_default_book",
      name: "Bookworm",
      description: "Knowledge seeker",
      type: "ICON" as const,
      rarity: "COMMON" as const,
      unlockMethod: "DEFAULT" as const,
      unlockCriteria: Prisma.JsonNull,
      sortOrder: 101,
    },
    {
      code: "icon_default_star",
      name: "Rising Star",
      description: "Destined for greatness",
      type: "ICON" as const,
      rarity: "COMMON" as const,
      unlockMethod: "DEFAULT" as const,
      unlockCriteria: Prisma.JsonNull,
      sortOrder: 102,
    },

    // ==================== UNLOCKABLE ICONS ====================
    {
      code: "icon_graduation_cap",
      name: "Graduate",
      description: "Academic excellence achieved",
      type: "ICON" as const,
      rarity: "EPIC" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "grade_complete" },
      sortOrder: 110,
    },
    {
      code: "icon_streak_flame",
      name: "Streak Flame",
      description: "Burning with dedication",
      type: "ICON" as const,
      rarity: "RARE" as const,
      unlockMethod: "STREAK" as const,
      unlockCriteria: { minStreak: 30 },
      sortOrder: 111,
    },
    {
      code: "icon_golden_crown",
      name: "Golden Crown",
      description: "Royalty among scholars",
      type: "ICON" as const,
      rarity: "LEGENDARY" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "scholars_year" },
      sortOrder: 112,
    },
    {
      code: "icon_math_pi",
      name: "Pi Symbol",
      description: "Mathematical prowess",
      type: "ICON" as const,
      rarity: "RARE" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "mastery_math_gold" },
      sortOrder: 113,
    },
    {
      code: "icon_lightning",
      name: "Lightning Bolt",
      description: "Speed and precision",
      type: "ICON" as const,
      rarity: "RARE" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "challenge_speed_demon" },
      sortOrder: 114,
    },

    // ==================== TITLES ====================
    {
      code: "title_learner",
      name: "Learner",
      description: "Every journey begins with a single step",
      type: "TITLE" as const,
      rarity: "COMMON" as const,
      unlockMethod: "DEFAULT" as const,
      unlockCriteria: Prisma.JsonNull,
      sortOrder: 200,
    },
    {
      code: "title_topic_master",
      name: "Topic Master",
      description: "Achieved Gold mastery in a topic",
      type: "TITLE" as const,
      rarity: "RARE" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "first_topic_master" },
      sortOrder: 201,
    },
    {
      code: "title_mathematician",
      name: "Mathematician",
      description: "Master of mathematical arts",
      type: "TITLE" as const,
      rarity: "EPIC" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "subject_champion_math" },
      sortOrder: 202,
    },
    {
      code: "title_math_wizard",
      name: "Math Wizard",
      description: "Numbers bend to your will",
      type: "TITLE" as const,
      rarity: "LEGENDARY" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "mastery_math_diamond" },
      sortOrder: 203,
    },
    {
      code: "title_dedicated_scholar",
      name: "Dedicated Scholar",
      description: "Unwavering commitment to learning",
      type: "TITLE" as const,
      rarity: "EPIC" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "streak_quarter_quest" },
      sortOrder: 204,
    },
    {
      code: "title_legendary_scholar",
      name: "Legendary Scholar",
      description: "Your dedication is the stuff of legends",
      type: "TITLE" as const,
      rarity: "LEGENDARY" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "streak_year_round" },
      sortOrder: 205,
    },
    {
      code: "title_founding_scholar",
      name: "Founding Scholar",
      description: "Among the first to embark on this journey",
      type: "TITLE" as const,
      rarity: "EPIC" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "special_founding_scholar" },
      sortOrder: 206,
    },
    {
      code: "title_polymath",
      name: "Polymath",
      description: "Master of many disciplines",
      type: "TITLE" as const,
      rarity: "EPIC" as const,
      unlockMethod: "BADGE" as const,
      unlockCriteria: { badgeCode: "explore_polymath" },
      sortOrder: 207,
    },
    {
      code: "title_explorer",
      name: "Explorer",
      description: "Seeker of knowledge across boundaries",
      type: "TITLE" as const,
      rarity: "RARE" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "curriculum_explorer" },
      sortOrder: 208,
    },
    {
      code: "title_storm_chaser",
      name: "Storm Chaser",
      description: "Thrives in the chaos of challenge",
      type: "TITLE" as const,
      rarity: "RARE" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "storm_chaser" },
      sortOrder: 209,
    },
    {
      code: "title_speed_scholar",
      name: "Speed Scholar",
      description: "Quick mind, quicker answers",
      type: "TITLE" as const,
      rarity: "RARE" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "speed_scholar" },
      sortOrder: 210,
    },
    {
      code: "title_dedicated",
      name: "The Dedicated",
      description: "1000 questions answered",
      type: "TITLE" as const,
      rarity: "UNCOMMON" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "thousand_club" },
      sortOrder: 211,
    },
    {
      code: "title_year_round_scholar",
      name: "Year-Round Scholar",
      description: "365 days of unbroken dedication",
      type: "TITLE" as const,
      rarity: "LEGENDARY" as const,
      unlockMethod: "ACHIEVEMENT" as const,
      unlockCriteria: { achievementCode: "scholars_year" },
      sortOrder: 212,
    },

    // ==================== PROFILE FRAMES ====================
    {
      code: "frame_default",
      name: "Standard Frame",
      description: "A simple, clean frame",
      type: "PROFILE_FRAME" as const,
      rarity: "COMMON" as const,
      unlockMethod: "DEFAULT" as const,
      unlockCriteria: Prisma.JsonNull,
      sortOrder: 300,
    },
    {
      code: "frame_bronze",
      name: "Bronze Frame",
      description: "A warm bronze border",
      type: "PROFILE_FRAME" as const,
      rarity: "COMMON" as const,
      unlockMethod: "XP" as const,
      unlockCriteria: { minXp: 500 },
      sortOrder: 301,
    },
    {
      code: "frame_silver",
      name: "Silver Frame",
      description: "A polished silver border",
      type: "PROFILE_FRAME" as const,
      rarity: "UNCOMMON" as const,
      unlockMethod: "XP" as const,
      unlockCriteria: { minXp: 2000 },
      sortOrder: 302,
    },
    {
      code: "frame_gold",
      name: "Gold Frame",
      description: "A prestigious gold border",
      type: "PROFILE_FRAME" as const,
      rarity: "RARE" as const,
      unlockMethod: "XP" as const,
      unlockCriteria: { minXp: 5000 },
      sortOrder: 303,
    },
    {
      code: "frame_platinum",
      name: "Platinum Frame",
      description: "A brilliant platinum border",
      type: "PROFILE_FRAME" as const,
      rarity: "EPIC" as const,
      unlockMethod: "XP" as const,
      unlockCriteria: { minXp: 15000 },
      sortOrder: 304,
    },
    {
      code: "frame_diamond",
      name: "Diamond Frame",
      description: "A dazzling diamond border",
      type: "PROFILE_FRAME" as const,
      rarity: "LEGENDARY" as const,
      unlockMethod: "XP" as const,
      unlockCriteria: { minXp: 50000 },
      sortOrder: 305,
    },
  ];

  for (const cosmetic of cosmetics) {
    await prisma.cosmeticItem.upsert({
      where: { code: cosmetic.code },
      update: cosmetic,
      create: cosmetic,
    });
  }
  console.log(`   ✅ Created ${cosmetics.length} cosmetic items\n`);

  // ============================================================================
  // SUMMARY
  // ============================================================================
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("🎉 Progression system seeded successfully!");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log(`   📛 Badges:       ${badges.length}`);
  console.log(`   🏆 Achievements: ${achievements.length}`);
  console.log(`   🎨 Cosmetics:    ${cosmetics.length}`);
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
